version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    restart: always
    container_name: audio-backend

  frontend:
    build: ./frontend
    ports:
      - "3001:3000"
    restart: always
    container_name: audio-frontend
    depends_on:
      - backend
